In [1]:
import numpy as np
import math
p1 = np.array([0,0])
p2 = np.array([1,1])
def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """
    x=[]
    for i in range(len(p1)):
        p= p2-p1
        x.append( math.pow(p[i],2))
        a = np.array(x)
    
        distancia = math.sqrt(np.sum(a))
    return distancia

In [2]:
distance(p1,p2)

1.4142135623730951

In [3]:
p1 = np.array([1,2])
p2 = np.array([1,1])
points = np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]])
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    P1 = points[0:] - p1
    P2 = points[0:] - p1
    PX = P1*P2
    y = np.sum(PX,axis = 1 )

    x = []
    for i in range(len(y)):
        x.append(math.sqrt(y[i]))
    n_dist = np.array(x)
    return n_dist

In [4]:
n_distances(p1, points)

array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

In [5]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
1 items had no tests:
    __main__
2 items passed all tests:
   3 tests in __main__.distance
   3 tests in __main__.n_distances
6 tests in 3 items.
6 passed and 0 failed.
Test passed.


TestResults(failed=0, attempted=6)